"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
var local_1 = require("next/font/local");
require("./globals.css");
var theme_provider_1 = require("@/providers/theme-provider");
var nohemi = (0, local_1.default)({
    src: "./fonts/InterVariable.woff2",
    variable: "--font-sans",
    display: "swap",
});
var geistMono = (0, local_1.default)({
    src: "./fonts/GeistMono.woff2",
    variable: "--font-geist-mono",
    display: "swap",
    style: ""
});
exports.metadata = {
    title: "Continuum",
    description: "Generated by create next app",
};
function RootLayout(_a) {
    var children = _a.children;
    return (<html lang="en" className={nohemi.variable} suppressHydrationWarning>
			<body className={"".concat(nohemi.variable, " ").concat(geistMono.variable, " antialiased")}>
				<theme_provider_1.ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					{children}
				</theme_provider_1.ThemeProvider>
			</body>
		</html>);
}
