# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: continuum.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'continuum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ontinuum.proto\x12\tcontinuum\" \n\x0bGameRequest\x12\x11\n\tgame_name\x18\x01 \x01(\t\"\x1e\n\x0cGameResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2O\n\x0bGameService\x12@\n\rGetGameStatus\x12\x16.continuum.GameRequest\x1a\x17.continuum.GameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'continuum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMEREQUEST']._serialized_start=30
  _globals['_GAMEREQUEST']._serialized_end=62
  _globals['_GAMERESPONSE']._serialized_start=64
  _globals['_GAMERESPONSE']._serialized_end=94
  _globals['_GAMESERVICE']._serialized_start=96
  _globals['_GAMESERVICE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
