# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import continuum_pb2 as continuum__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in continuum_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGameStatus = channel.unary_unary(
                '/continuum.GameService/GetGameStatus',
                request_serializer=continuum__pb2.GameRequest.SerializeToString,
                response_deserializer=continuum__pb2.GameResponse.FromString,
                _registered_method=True)


class GameServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetGameStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGameStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameStatus,
                    request_deserializer=continuum__pb2.GameRequest.FromString,
                    response_serializer=continuum__pb2.GameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'continuum.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('continuum.GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGameStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continuum.GameService/GetGameStatus',
            continuum__pb2.GameRequest.SerializeToString,
            continuum__pb2.GameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MutexServiceStub:
    """Experiment 4: Mutual Exclusion Service (Ricart-Agrawala Algorithm)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestAccess = channel.unary_unary(
                '/continuum.MutexService/RequestAccess',
                request_serializer=continuum__pb2.MutexRequest.SerializeToString,
                response_deserializer=continuum__pb2.MutexResponse.FromString,
                _registered_method=True)


class MutexServiceServicer:
    """Experiment 4: Mutual Exclusion Service (Ricart-Agrawala Algorithm)
    """

    def RequestAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=continuum__pb2.MutexRequest.FromString,
                    response_serializer=continuum__pb2.MutexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'continuum.MutexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('continuum.MutexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MutexService:
    """Experiment 4: Mutual Exclusion Service (Ricart-Agrawala Algorithm)
    """

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continuum.MutexService/RequestAccess',
            continuum__pb2.MutexRequest.SerializeToString,
            continuum__pb2.MutexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LockServiceStub:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLock = channel.unary_unary(
                '/continuum.LockService/AcquireLock',
                request_serializer=continuum__pb2.LockRequest.SerializeToString,
                response_deserializer=continuum__pb2.LockReply.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/continuum.LockService/ReleaseLock',
                request_serializer=continuum__pb2.LockRequest.SerializeToString,
                response_deserializer=continuum__pb2.LockReply.FromString,
                _registered_method=True)


class LockServiceServicer:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    def AcquireLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=continuum__pb2.LockRequest.FromString,
                    response_serializer=continuum__pb2.LockReply.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=continuum__pb2.LockRequest.FromString,
                    response_serializer=continuum__pb2.LockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'continuum.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('continuum.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continuum.LockService/AcquireLock',
            continuum__pb2.LockRequest.SerializeToString,
            continuum__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continuum.LockService/ReleaseLock',
            continuum__pb2.LockRequest.SerializeToString,
            continuum__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub:
    """--- Experiment 6: Load Balancing (Least Connections) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleRequest = channel.unary_unary(
                '/continuum.WorkerService/HandleRequest',
                request_serializer=continuum__pb2.WorkRequest.SerializeToString,
                response_deserializer=continuum__pb2.WorkReply.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """--- Experiment 6: Load Balancing (Least Connections) ---
    """

    def HandleRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleRequest,
                    request_deserializer=continuum__pb2.WorkRequest.FromString,
                    response_serializer=continuum__pb2.WorkReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'continuum.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('continuum.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """--- Experiment 6: Load Balancing (Least Connections) ---
    """

    @staticmethod
    def HandleRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continuum.WorkerService/HandleRequest',
            continuum__pb2.WorkRequest.SerializeToString,
            continuum__pb2.WorkReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplicaServiceStub:
    """--- Experiment 7: Eventual Consistency via Gossip Replication + Last-Write-Wins ---
    Replicated key-value style store. Each replica exposes the same
    three RPCs to clients AND to its peer replicas.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveValue = channel.unary_unary(
                '/continuum.ReplicaService/SaveValue',
                request_serializer=continuum__pb2.ValueUpdate.SerializeToString,
                response_deserializer=continuum__pb2.SaveAck.FromString,
                _registered_method=True)
        self.SyncUpdate = channel.unary_unary(
                '/continuum.ReplicaService/SyncUpdate',
                request_serializer=continuum__pb2.ValueUpdate.SerializeToString,
                response_deserializer=continuum__pb2.SaveAck.FromString,
                _registered_method=True)
        self.GetValue = channel.unary_unary(
                '/continuum.ReplicaService/GetValue',
                request_serializer=continuum__pb2.ValueQuery.SerializeToString,
                response_deserializer=continuum__pb2.ValueState.FromString,
                _registered_method=True)


class ReplicaServiceServicer:
    """--- Experiment 7: Eventual Consistency via Gossip Replication + Last-Write-Wins ---
    Replicated key-value style store. Each replica exposes the same
    three RPCs to clients AND to its peer replicas.
    """

    def SaveValue(self, request, context):
        """client -> replica (local write)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncUpdate(self, request, context):
        """replica -> replica (gossip)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValue(self, request, context):
        """read current state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveValue,
                    request_deserializer=continuum__pb2.ValueUpdate.FromString,
                    response_serializer=continuum__pb2.SaveAck.SerializeToString,
            ),
            'SyncUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncUpdate,
                    request_deserializer=continuum__pb2.ValueUpdate.FromString,
                    response_serializer=continuum__pb2.SaveAck.SerializeToString,
            ),
            'GetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValue,
                    request_deserializer=continuum__pb2.ValueQuery.FromString,
                    response_serializer=continuum__pb2.ValueState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'continuum.ReplicaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('continuum.ReplicaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaService:
    """--- Experiment 7: Eventual Consistency via Gossip Replication + Last-Write-Wins ---
    Replicated key-value style store. Each replica exposes the same
    three RPCs to clients AND to its peer replicas.
    """

    @staticmethod
    def SaveValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continuum.ReplicaService/SaveValue',
            continuum__pb2.ValueUpdate.SerializeToString,
            continuum__pb2.SaveAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continuum.ReplicaService/SyncUpdate',
            continuum__pb2.ValueUpdate.SerializeToString,
            continuum__pb2.SaveAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continuum.ReplicaService/GetValue',
            continuum__pb2.ValueQuery.SerializeToString,
            continuum__pb2.ValueState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
